directory_of_datasets: "/home/leah/research_analysis/cowpi_testing/cowpi_workflow_container_work/initial_data/"
single_or_multiple_datasets: "multiple"
copy_number_table_file: "/home/leah/research_analysis/cowpi_testing/CowPI/CowPi_V1.0_16S_precalculated.tab"
ko_table: "/home/leah/research_analysis/cowpi_testing/CowPI/CowPi_V1.0_ko_precalc1.tab"
16s_sequence_table: "/home/leah/research_analysis/cowpi_testing/CowPI/CowPi_all_rumen_16s_combined_gap_rem.fas"
threads: 6
